### ISSUE TITLE
10808 - 알파벳 개수

### ISSUE THREAD

**Issue by 42-mki** [42-mki/algorithm#45]
https://www.acmicpc.net/problem/10808

**Comment by 42-mki** [comment]
2021-12-25
문제 분석: 1분
자료구조: array

# Algorithm

1. 알파벳만큼 array를 만든다.
2. S를 순회하면서 element - 'a'로 array의 index를 구하고 array에서 해당 index 원소를 ++
3. array를 출력

**Comment by 42-mki** [comment]
# C++

```
#include <iostream>
#include <string>

int main(){
  std::string S;
  int array[26];

  for (int i = 0; i < 26; i++) {
    array[i] = 0;
  }

  std::cin >> S;
  for (std::string::iterator iter = S.begin(); iter < S.end(); iter++) {
    array[*iter - 'a']++;
  }

  for (int i = 0; i < 26; i++) {
    std::cout << array[i] << " ";
  }
}
```

**Comment by newmki** [comment]
# 알고리즘 1

- 자료구조: 배열
- 시간복잡도: O(N)
- 문제 이해: 1분
- 문제 풀이: 1분
- 문제 구현: 3분

1. 입력 받은 문자열을 size만큼 순회하면서 각 알파벳에 해당하는 index를 ++ O(N)
2. arr을 순회하며 count출력
